### PR TITLE
Fix ESP32 SPI compile when using PlatformIO

### PR DESCRIPTION
**Pull request by barthogenes**
I had the same issues as @ntwallace [here](https://github.com/FastLED/FastLED/pull/1047#issuecomment-710481295) and @stickperson [here](https://github.com/FastLED/FastLED/pull/1047#issuecomment-951326963) so I recreated @ntwallace's pull request. I have tested these changes on my own ESP32 + Platformio + VSCode setup and it fixed my errors, so I think it is ready to be contributed to the master branch. :smiley: 

Changes (from https://github.com/ntwallace/FastLED/pull/1#issue-723512406):
- Include Arduino library "SPI.h"
- Moved SPIClass ledSPI into class ESP32SPIOutput as private member

### CODE REVIEW

**Comment by barthogenes** [comment]
Weird, I did test these changes in my own PlatfromIO project and I did not get any build errors.
Maybe you can try to make everything `static`? I tried doing that in [this commit](https://github.com/barthogenes/FastLED/commit/6a7f51370888c23e706873dcac6ca95c71329d21) and this also did not give me any build errors.
I am not very proficient with C++ so I am just trying some things out here 😀

**Comment by stickperson** [comment]
Any update on this?

**Comment by samguyer** [comment]
Hi all! Sorry, it's been so long since we were able to look at PRs. Is this something we still need?

**Comment by steveroch-rs** [comment]
> Hi all! Sorry, it's been so long since we were able to look at PRs. Is this something we still need?

I am still facing this issue. Though I have not empirically verified when this arises. I will have another look into it the coming weeks/months when I am free from university. I am also willing to work on this together with you.

**Comment by samguyer** [comment]
OK, great. Thank you! Keep us posted.

**Comment by samguyer** [comment]
Merging this change! Sorry it took so long to get it incorporated. We are actively working on ESP32 support, so trying to get everything in. Thank you for your contribution!

**Pull request merged**
