### PR TITLE
fix for glitching LEDs caused by NMI

### PR DESCRIPTION
**Pull request by sascha432**
This checks if the 24bit sequence was interrupted by a NMI and aborts the frame. If 23 bit or less are sent followed by a reset timeout, the bits are ignored by the LEDs.

It also adds "mWait" to ensure the WAIT_TIME between frames is long enough.

### CODE REVIEW

**Comment by sascha432** [comment]
The last commit changes WAIT_TIME to ensure that the LEDs detect the gap between frames. It seems some require a little over 70µs

**Comment by kriegsman** [comment]
Thank you so much for your work on this, @sascha432: for tracking it down, for making the fix, for testing it, and for contributing this PR.  It's going to help a lot of people, and your contribution to FastLED is very much appreciated!

**Comment by DmytroKorniienko** [comment]
@sascha432 @kriegsman 
Unfortunately this fix absolutely not working for me:
1. Fix + SDK3.0.0+ -> blank/freeze matrix
2. Fix + platform = espressif8266@2.6.3 -> reboot on yield() in loop or normal work with commented out yield()

Same code before fix:
1. SDK3.0.0+ -> flickering of first led, all other work as expected
2.  platform = espressif8266@2.6.3 -> all work as expected

* I tried to change WAIT_TIME 50...150 without success

Any suggestions? Project with issue:
https://github.com/DmytroKorniienko/FireLamp_JeeUI

**Comment by macegr** [comment]
Backing up @DmytroKorniienko, this PR breaks FastLED for me on 2.x ESP core and still doesn't work on 3.x core.

**Comment by sascha432** [comment]
@DmytroKorniienko 
I found an os_intra_lock() call without unlock() which might cause your yield() issue.
Not a new bug, but maybe the SDK3.0.0 behaves differently.

https://github.com/FastLED/FastLED/pull/1274

**Pull request merged**
