### PR TITLE
renesas: initial porting for UNO R4

### PR DESCRIPTION
**Pull request by facchinm**
Tested on Neopixel-like (clockless)

### CODE REVIEW

**Review by zackees — APPROVED** [review]
Looked over the code. Looks good. Please @ me if there are follow up commits.

**Comment by OoDeLally** [comment]
Thanks for your contribution!

I've tried that branch with a R4 Minima and a WS2811.
```
FastLED.addLeds<WS2811, 8>(leds, NUM_LEDS);
// or
FastLED.addLeds<NEOPIXEL, 8>(leds, NUM_LEDS);
```

Regardless or the chosen color, the blue and green leds stay up constantly.
The red led is behaving as expected.

I can tell this is not an issue with my hardware since the same setup works with fine with with a Nano.

Does it ring a bell?

Thanks!

**Comment by kriegsman** [comment]
Thank you for this really helpful contribution, and thank you for your help with the FastLED library!

**Comment by ocack** [comment]
Hello,

I have a UNO R4 and a WS2811 strip led.
The actual FastLed release doesn't work with this configuration.
I tried without success this ticket : #1554 #1523 

I can help because I have the hardware and I'am not a novice in C Programmation.
I just need renesas and WS2811 specification.

Any help would be appreciated.
Regards

**Comment by Pythagolix** [comment]
I tested it with uno r4 minima and it does compile, but does not do anything to actually control the LED colors.  I could help out as well, just tell me where to start looking in the code to modify.

**Comment by ocack** [comment]
Can anybody help me for this issue ?
Difficult to beleive that I am the only one that interfaces an Arduino R4 with FastLed and a strip WS2811 !?
I would like to help the community to move forward on that issue.
Which tests can I do ?
Which documentation do I need for trying to fixing that ?
Regards

**Comment by OoDeLally** [comment]
> Can anybody help me for this issue ? Difficult to beleive that I am the only one that interfaces an Arduino R4 with FastLed and a strip WS2811 !? I would like to help the community to move forward on that issue. Which tests can I do ? Which documentation do I need for trying to fixing that ? Regards

It is working fine for me with R4 and FastLED 3.6.0 (branch `master`).

```c
FastLED.addLeds<WS2812, LED_DATA_1_PIN>(leds, TILE_COUNT);
```

What issues are you facing exactly?

**Comment by dugi07** [comment]
[ocack](https://github.com/ocack) asked about WS2811(12v), not WS28**12**
I've got same issue: "This platform isn't recognized by FastLED... yet.  See comments in FastLED/led_sysdefs.h for options."
Any idea how to define head(LED_TYPE etc) for ws2811?

**Comment by dugi07** [comment]
FastLED 3.6.0
Arduino UNO R4 Wifi
Arduino IDE 2.3.2 (Exaple->fastLed->RGBSetDemo)
```
#include <FastLED.h>
#define NUM_LEDS 40
CRGBArray<NUM_LEDS> leds;
void setup() {
  FastLED.addLeds<WS2812,2>(leds, NUM_LEDS);
}
void loop(){ 
  static uint8_t hue;
  for(int i = 0; i < NUM_LEDS/2; i++) {   
    leds.fadeToBlackBy(40);
    leds[i] = CHSV(hue++,255,255); 
    leds(NUM_LEDS/2,NUM_LEDS-1) = leds(NUM_LEDS/2 - 1 ,0);
    FastLED.delay(33);
  }
}
```


In file included from d:\.../FastLED.h:51:0,
                 from D:\..\RGBSetDemo.ino:5:
d:\...\FastLED\src/led_sysdefs.h:61:2: error: #error "This platform isn't recognized by FastLED... yet.  See comments in FastLED/led_sysdefs.h for options."
 #error "This platform isn't recognized by FastLED... yet.  See comments in FastLED/led_sysdefs.h for options."
  ^~~~~
exit status 1

Compilation error: exit status 1

**Any ideas?**

**Comment by OoDeLally** [comment]
are you using the master branch?
The version served by the arduino IDE may be older

**Comment by dugi07** [comment]
I never download older version of FastLED. What do u mean master brenach? All lib and sketch in same place?

**Pull request merged**
