### PR TITLE
nRF52 support

### PR DESCRIPTION
**Pull request by henrygab**
FastLED support requires three parts:
1. FastPIN
2. FastSPI
3. Clockless

This pull requests provides the **_first two_** of these: FastPIN and FastSPI.

@focalintent, I will definitely need help with clockless...

### CODE REVIEW

**Comment by henrygab** [comment]
Useful items that can be relied upon from [nrfx](https://github.com/NordicSemiconductor/nrfx), which is used by the BSPs for the nRF52 series:
* [nrf_delay_us(uint32_t number_of_us)](https://github.com/adafruit/Adafruit_nRF52_Bootloader/blob/df58b8512e3e73805e9a96b796b8610533098aa0/lib/sdk/components/drivers_nrf/delay/nrf_delay.h#L56-L65)
* [nrf_delay_ms(uint32_t number_of_ms)](https://github.com/adafruit/Adafruit_nRF52_Bootloader/blob/df58b8512e3e73805e9a96b796b8610533098aa0/lib/sdk/components/drivers_nrf/delay/nrf_delay.h#L68-L81)
* [NRFX_RTC_US_TO_TICKS(us,freq)](https://github.com/NordicSemiconductor/nrfx/blob/9d68726e41c321f1772c187bd12d82f5b13104f1/drivers/include/nrfx_rtc.h#L49-L50)

Nordic provides a [guide](http://infocenter.nordicsemi.com/pdf/nRF52_Series_Migration_v1.0.pdf) ([html](http://infocenter.nordicsemi.com/topic/com.nordic.infocenter.nrf52/dita/nrf52/migration/preface.html)) to migrating from the nRF51 (which uses arm\common\m0clockless.h) to the nRF52.  Here's some takeaways:

##### Performance
* The processor for nRF52 is an ARM **Cortex M4F**.
* nRF52 processor runs at **64MHz** (vs 16MHz of nRF51).
* The APB system (interconnect to peripherals / flash) still runs at 16MHz.
  * Code should interleave APB writes (peripherals) with non-memory operations for highest throughput
    * **_Reading_** from peripherals on APB system may take relatively longer (clock cycles)
    * Cortex-M4 processor uses a write buffer for the APB system.
    * The write buffer allows the core, after writing to the APB, to continue to execute code that does not access the system bus.
    * Any read from the APB system implies a wait for the write buffer to complete.
  * **_Sequential_** code usually can run without stalling the pipeline
    * Executing code from flash may have a wait-state penalty due to the 16MHz APB
    * The exact wait-state penalty also depends on whether instruction cache is enabled or not (it's enabled on Adafruit bootloader)
    * Cortex-M4F does prefetching, so sequential code usually can run without stalling the pipeline
* The nRF52 has five timers (vs. 3 with nRF51)
  * All five timers support all bit modes (8,16, 24, 32)
  * Therefore, no longer a requirement to use NRF_TIMER1 to get 32-bit timer as on nRF51
  * The timers use a the **_16MHz clock_**
* SysTick timer was added
* Two RTC peripherals (vs. one in nRF51)
  * the RTC appear to use a [**_32MHz clock_**](https://github.com/NordicSemiconductor/nrfx/blob/9d68726e41c321f1772c187bd12d82f5b13104f1/hal/nrf_rtc.h#L52).

**Comment by focalintent** [comment]
Thank you for this!  I'm completely underwater with a number of projects so it will be a few weeks (at the earliest) before I'll be able to dive into integrating this and filling in the clockless bits.  (Just wanted to let you know that I had seen it and wasn't ignoring it)

**Comment by henrygab** [comment]
@focalintent - **_REALLY_** appreciate the note, thanks!  I will attempt to stay silent for next few weeks.  Good luck!

P.S. - If I can provide any information that would make it easier for you to implement clockless, let me know.

**Comment by henrygab** [comment]
Additional information for anyone wanting to add Cortex M4 clockless support:

* [Cortex M4 Technical Reference Manual  (TRM) (pdf)]https://static.docs.arm.com/100166/0001/arm_cortexm4_processor_trm_100166_0001_00_en.pdf)
* [Cortex M4 Technical Reference Manual (TRM) (html)](https://developer.arm.com/docs/100166/0001)
* [ARM v7-M Architecture Reference Manual (pdf)](https://static.docs.arm.com/ddi0403/e/DDI0403E_B_armv7m_arm.pdf)

Specifically, the following sections may be of interest:
1. Section 3.3.3, which highlights LOAD/STORE timing
2. Section 3.3.1, table 3-1, which lists cycle timing for instructions
3. the architecture reference manual, A.7.7, Thumb Instructions (esp. IT instruction, for making up to four next instructions conditional....)

**Comment by henrygab** [comment]
Good news.  I've implemented a version of clockless.  I've some minor cleanup, and then I can push it into the nrfx branch.

I've tested **_every_** clockless chipset definition's output with an oscilloscope.
(note: I have a new PR that will address some issues found with chipset.h there....)

Caveats:
* Currently hard-coded to 144 LEDs maximum per string.
* Currently hard-coded to use of only PWM0.

Future work includes:
1. Enabling user-configured maximum LED string length, to reduce RAM usage.
2. Enabling substantially infinite LED string length (method designed, not written or tested yet)

**Comment by henrygab** [comment]
Closing this one as points to a now-defunct branch.
See new PR #802

**Pull request closed without merging**
