### PR TITLE
Code formatting cleanups; markdown corrections

### PR DESCRIPTION
**Pull request by MartyMacGyver**
**If you view the diff [with whitespace changes hidden](https://github.com/FastLED/FastLED/pull/1031/files?diff=split&w=1), it's much easier to see the few complex formatting changes.**

- Improve formatting consistency
- Fix comment/docstring/markdown typos
- Remove unused file

Note: there are a lot of changes in this PR, but they should all be non-functional changes (that is, any change should have zero impact of compiled code). I used the most consistent coding styles in the repo for consistency. The goal of this is to make the code easier to read and maintain going forward (across source files as well as within a given source file).

For the formatting update to the large table in `noise.cpp`, I did verify independently that the initialization data is identical before and after this change.

### CODE REVIEW

**Comment by MartyMacGyver** [comment]
Note: one thing I did NOT do here is change indentation tab characters to 4-space "tabs" in all files. Lots of files indent with tabs, and lots with spaces. I did my best to preserve the intent in a given file, but IMHO it'd be preferable to switch to 4-space indentation rather than the tab character for everything EXCEPT the .ino files (which are normally 2-space tabs and which I didn't touch here)

**Comment by MartyMacGyver** [comment]
@kriegsman I'm not sure what the merge cadence is these days, but I'd like to get these foundational cleanups merged.

**Comment by jasoncoon** [comment]
@MartyMacGyver thanks for the PR!  I'm going to try to find time to help sort through the PR backlog.  This one looks good to me, but I'll pull your branch and test compiling and running on a few different platforms just in case.

Questions:

1. Did you use Arduino to perform the reformatting?
2. I know you say the changes are non-functional, and I agree they appear to be, but have you already tested on any particular platforms?

**Comment by MartyMacGyver** [comment]
Yep - this was my basis for some investigation work I was doing on Teensy-related bugs.

**Comment by MartyMacGyver** [comment]
And the formatting was primarily done by hand in VSCode, not Arduino. Where relevant, I used the pre-existing format for the given target.

The goal here was to eliminate inconsistencies in formatting.

**Comment by kriegsman** [comment]
Thanks for the help keeping things organized and consistent!

**Pull request merged**
