### PR TITLE
Added support for Seeed Xiao NRF52840 

### PR DESCRIPTION
**Pull request by paulhayes**
Added nrf52840 variant, the Xiao Nrf52840 ( not the Sense version yet )

### CODE REVIEW

**Comment by zackees** [comment]
Wow thank you! Christmas came early!

**Comment by zackees** [comment]
Cool, I'm adding a build badge and including this in the pull requests to ensure this doesn't break now going forward.

**Comment by zackees** [comment]
Sorry but it doesn't build with any known platformio configuration. Can you provide one?

[nrf52840_dk](https://github.com/FastLED/FastLED/actions/workflows/build_nrf52840_dk.yml)

You can test this yourself by clone the main repo and then running:

` ./compile nrf52840_dk`

You'll find the board definition in `ci/ci/boards.py`

```python
NRF52840 = Board(
    board_name="nrf52840_dk",
    platform="nordicnrf52",
    platform_needs_install=True,
)
```

But if you can provide me a platformio.ini file then we can at least lock down a builder that will work for this.

**Comment by zackees** [comment]
It's can't load these files:

```C++

#include <nrf.h>
#include <nrf_spim.h>   // for FastSPI
#include <nrf_pwm.h>    // for Clockless
#include <nrf_nvic.h>   // for Clockless / anything else using interrupts
```

Not sure how to get them or what packages are necessary. Platformio latest doesn't work out of the box.

**Comment by paulhayes** [comment]
I'm so sorry, I completely forgot I'm using a fork of the nordicnrf52 platform that adds support for the seeed Xiao Nrf52840 board
https://github.com/platformio/platform-nordicnrf52/pull/151
It's been waiting to be merged in for two years. I've given a little nudge to see if we can get it merged in finally.

For now my platformio.ini looks like this
```
platform = https://github.com/maxgerhardt/platform-nordicnrf52
board = xiaoble_adafruit 
framework = arduino
```

**Comment by zackees** [comment]
Dude, thank you so much for your help! The board now compiles and now i've added it as a test for all pull requests.

Thanks again!

**Comment by paulhayes** [comment]
You're welcome @zackees, and thanks for the kind messages. I'll definitetly be returning to nrf52 boards and FastLED, so I'll try to keep on top of anything issues that crop up.

**Pull request merged**
