### PR TITLE
Add rp2040 workarounds to avoid register warnings

### PR DESCRIPTION
**Pull request by Zitt**
- add rp2040 platform
- rp2040: fix some issues with fastpin/spi bitbanging (thread safety and accidental use of wrong reg for hival,loval)
- rp2040: support using m0clockless output implementation for >8 strips
- rp2040: switch to custom PIO program that doesn't use sideset avoiding sideset means that we double the max instruction delay, which should increase our timing resolution it also means that there's no longer a separately-licensed block of code included

### CODE REVIEW

**Comment by Zitt** [comment]
workarounds to suppress  
warning: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
with https://github.com/earlephilhower/arduino-pico under Arduino 2.0.0-rc6.

**Comment by connornishijima** [comment]
Sure would love to use RP2040 on FastLED some time in the next century, lol.

**Comment by kriegsman** [comment]
This is a great contribution -- thank you for the new platform support, and all the assistance getting it up and running!  Thank you again for your help with FastLED!

**Comment by connornishijima** [comment]
FastLED is on a merging ROLL today, woohoo!

Any ETA for an official 3.6.x release with the new docs and RP2040 support?

**Comment by 1988xd** [comment]
In file included from d:\Arduino\libraries\FastLED\src/FastLED.h:58,
                 from D:\Arduino\Raspberry Pi Pico\OneButtonTest\OneButtonTest.ino:4:
d:\Arduino\libraries\FastLED\src/fastpin.h:293:71: warning: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
  293 |  inline static void fastset(REGISTER port_ptr_t port, register port_t val) __attribute__ ((always_inline)) { }
      |                                                                       ^~~
In file included from d:\Arduino\libraries\FastLED\src/FastLED.h:59,
                 from D:\Arduino\Raspberry Pi Pico\OneButtonTest\OneButtonTest.ino:4:
d:\Arduino\libraries\FastLED\src/fastspi_types.h:44:105: warning: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
   44 |     static __attribute__((always_inline)) inline uint8_t adjust(REGISTER uint8_t data, register uint8_t scale) { return scale8(data, scale); }
      |                                                                                                         ^~~~~
In file included from d:\Arduino\libraries\FastLED\src/platforms/arm/rp2040/fastled_arm_rp2040.h:5,
                 from d:\Arduino\libraries\FastLED\src/platforms.h:38,
                 from d:\Arduino\libraries\FastLED\src/FastLED.h:62,
                 from D:\Arduino\Raspberry Pi Pico\OneButtonTest\OneButtonTest.ino:4:
d:\Arduino\libraries\FastLED\src/platforms/arm/rp2040/fastpin_arm_rp2040.h:28:42: warning: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
   28 |   inline static void set(register port_t val) __attribute__ ((always_inline)) { sio_hw->gpio_out = val; }
      |                                          ^~~
d:\Arduino\libraries\FastLED\src/platforms/arm/rp2040/fastpin_arm_rp2040.h:34:45: warning: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
   34 |   inline static void hi(register port_ptr_t port) __attribute__ ((always_inline)) { hi(); }
      |                                             ^~~~
d:\Arduino\libraries\FastLED\src/platforms/arm/rp2040/fastpin_arm_rp2040.h:35:45: warning: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
   35 |   inline static void lo(register port_ptr_t port) __attribute__ ((always_inline)) { lo(); }
      |                                             ^~~~
d:\Arduino\libraries\FastLED\src/platforms/arm/rp2040/fastpin_arm_rp2040.h:36:50: warning: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
   36 |   inline static void fastset(register port_ptr_t port, register port_t val) __attribute__ ((always_inline)) { *port = val; }
      |                                                  ^~~~
d:\Arduino\libraries\FastLED\src/platforms/arm/rp2040/fastpin_arm_rp2040.h:36:72: warning: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
   36 |   inline static void fastset(register port_ptr_t port, register port_t val) __attribute__ ((always_inline)) { *port = val; }
      |                                                                        ^~~
In file included from d:\Arduino\libraries\FastLED\src/FastLED.h:75,
                 from D:\Arduino\Raspberry Pi Pico\OneButtonTest\OneButtonTest.ino:4:
d:\Arduino\libraries\FastLED\src/fastspi.h:172:23: note: '#pragma message: Forcing software SPI - no hardware SPI for you!'
  172 | #      pragma message "Forcing software SPI - no hardware SPI for you!"
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by Dantali0n** [comment]
Looking forward to the new version release so I can try this out! Many thanks for your contribution and thank you maintainers for putting it all together.

**Comment by Dantali0n** [comment]
Is there any way in platformio to be able to already test this, I will get two arduino nano rp2040 connects in about 3 days.

**Comment by Kinue72** [comment]
Sorry but I can't compile with **FASTLED_ALLOW_INTERRUPTS** = **1**
```
C:\Users\username\AppData\Local\Temp\cc8mt6TA.s: Assembler messages:
C:\Users\username\AppData\Local\Temp\cc8mt6TA.s:1299: Error: invalid offset, value too big (0x000004B0)
C:\Users\username\AppData\Local\Temp\cc8mt6TA.s:1305: Error: invalid offset, value too big (0x000004A8)
*** [.pio\build\pico\src\main.cpp.o] Error 1
```
But with ** FASTLED_ALLOW_INTERRUPTS** = 0 it compiles just fine.

**Pull request merged**
