### PR TITLE
EVERY_N_MICROSECONDS fixes and addition

### PR DESCRIPTION
**Pull request by NicoHood**
As discussed in the chat I got a few minor fixes ready for the every n micros function.

Also I'd like to introduce a new feature called `intervals` which keeps track of the missed updates and also precisely counts the frames, so you can always get back in sync later.

lets say you have a timeline starting with 0
you want updates every 10 ms.
so you'd optimally want 0,10,20,30,40

blink without delay will always add +10 ms, but if a frame is slower, the delay will be added and not ignored in the next step
so you have 0, 10, 21, 31, 42, 52, 62, 75, etc

and my code does cover this and recovers to the original values. it tries to stay as close to the 10ms interval as posible:
0, 10, 21, 30, 41, 50, 60, 73

Here is a quick and dirty demo:

``` cpp
#include "FastLED.h"

#define led 11
#define led2 10
#define button 8

int brightness = 0;    // how bright the LED is
int fadeAmount = 5;    // how many points to fade the LED by
int brightness2 = 0;    // how bright the LED is
int fadeAmount2 = 5;    // how many points to fade the LED by

void setup() {
  // put your setup code here, to run once:
  pinMode(button, INPUT_PULLUP);
  pinMode(led, OUTPUT);
  pinMode(led2, OUTPUT);
}

void loop() {
  // press the button to stop the animation
  if (digitalRead(button)) {
    int n = 4;
    if (n == 0) {
      // wait for 30 milliseconds to see the dimming effect
      delay(30);
    }
    else if (n == 1) {
      // blink without delay like
      EVERY_N_MILLISECONDS( 30 ) {
        fade(1);
      }
    }
    else if (n == 2) {
      // blink without delay as normal instantiation
      static CEveryNMilliseconds m(30);
      if (m.ready()) {
        fade(1);
      }
    }
    else if (n == 3) {
      // new interval funktion at its basic
      static CEveryNMilliseconds m(30);
      if (m.intervals()) {
        fade(1);
      }
    }
    else if (n == 4) {
      // new interval function will count how many fades were missed
      // those iterations will be added and the led is irght in place again
      static CEveryNMilliseconds m(30);
      auto intervals = m.intervals();
      fade(intervals);
    }
  }

  // blink without delay like
  // independant led will blink as reference
  EVERY_N_MILLISECONDS( 30 ) {
    fade2(1);
  }
}

void fade(uint32_t interval) {
  for ( uint32_t i = 0; i < interval; i++) {
    // change the brightness for next time through the loop:
    brightness = brightness + fadeAmount;

    // reverse the direction of the fading at the ends of the fade:
    if (brightness == 0 || brightness == 255) {
      fadeAmount = -fadeAmount ;
    }
  }

  if (interval) {
    // put your main code here, to run repeatedly:
    analogWrite(led, brightness);
  }
}

void fade2(uint32_t interval) {
  for ( uint32_t i = 0; i < interval; i++) {
    // change the brightness for next time through the loop:
    brightness2 = brightness2 + fadeAmount2;

    // reverse the direction of the fading at the ends of the fade:
    if (brightness2 == 0 || brightness2 == 255) {
      fadeAmount2 = -fadeAmount2 ;
    }
  }

  if (interval) {
    // put your main code here, to run repeatedly:
    analogWrite(led2, brightness2);
  }
}
```

### CODE REVIEW

**Comment by NicoHood** [comment]
I do not know why there are two commits in the history that are not from me. I guess they were removed?

Anyways, I'd like to **push** @focalintent

**Comment by focalintent** [comment]
This is mark's code - i'll let him merge/pull it when he's had a chance to go through it.

**Comment by NicoHood** [comment]
Okay. Do you know what happened with the other 2 commits? Have you force pushed something to the master? I have to remove it then.

**Comment by NicoHood** [comment]
I fixed the PR (those 2 unwanted commits) and also added zero division check now. I used -1 to get a 0xFFFFFFFF in most cases. Is this method okay?

**Comment by chrisparton1991** [comment]
Hey @NicoHood, just a friendly reminder that there's a conflict here that needs to be resolved.

**Comment by NicoHood** [comment]
Yup. Its been a long time. I aint got time to resolve and test the conflict. It seems the merge is not that important and I didnt work with leds for a long time now.

**Comment by chrisparton1991** [comment]
No problem, thanks @NicoHood. Should this be closed, @kriegsman?

**Pull request closed without merging**
