### PR TITLE
Add stub implementation for local testing

### PR DESCRIPTION
**Pull request by sethtroisi**
I wanted to test some of my patterns on my computer were it's much quicker to compile, test, tune, and iterate.

So I wrote a little wrapper [demo_simple.cpp](https://gist.github.com/sethtroisi/079bc61d5d905feed9026f168d592227) around  FastLED so that I could see the pixels on my computer (while still using 99% of my same pattern code).

I'd love to upstream the FastLED Controller Stub if you consider it reasonable. I think I got the right pieces in the right place and I'm happy to change if there are things I've messed up.

FastLED continues to make my art fabulous!

---

EDIT: Looking at the tests using `defined(__x86_64__)` might conflict on some platforms, I'm open to better solutions; possible passing in `-DSTUB_IMPL` or adding a setting a new `#define` to fastled_config.h

### CODE REVIEW

**Comment by marmilicious** [comment]
Do you have a video of this running?

**Comment by sethtroisi** [comment]
This is a video of demo_simple with some extra delay added (so it doesn't run at 10,000 FPS)
https://user-images.githubusercontent.com/10172976/155034306-7d4a26b7-318b-4d02-9124-a8b36c7d9452.mp4

And this is a screenshot of an effect I'm tuning with 50x100 strips
Screenshot from 2022-02-08 02-13-28

**Comment by marmilicious** [comment]
Pretty cool, thank you for the video and screenshot.

**Comment by Jueff** [comment]
Hello @sethtroisi. I like this idea very much, could you please share a description of your build environment containing tools, scripts/makefile?

Thank you!

**Comment by sethtroisi** [comment]
I have three versions of my project all sharing the same lights driving code. I target esp32, photon particle, and do tuning in my desktop. I do all the programming in VS Code.

VSCode has an extension for the photon particle it simple take all the cpp and h files and passes everything to gcc, compiling everything without any config.

For the esp32 I cloned a FastLED demo from espresso which uses cmake. The build tool is ninja(?).

Finally and most simple is my new desktop visualizer. I tend to compile the FastLED source files to object files then use `ar` to turn that into a library which speeds up compilation but it's also possible to build with `g++ demo_simple.cpp -I~/Projects/FastLED/src -lsfml-graphics -lsfml-window -lsfml-system -pthread` where `demo_simple.cpp`is linked above.

Let me know if other details would be useful.

**Comment by zackees** [comment]
Thanks, merged in manually:

https://github.com/FastLED/FastLED/pull/1685

**Comment by sethtroisi** [comment]
Thanks for merging this. It's so nice to have fewer branches and get to use a clean upstream :)

**Comment by zackees** [comment]
What's thsi effect called btw?

**Pull request closed without merging**
