### PR TITLE
Add ATtiny 0/1 series

### PR DESCRIPTION
**Pull request by freemovers**
Added the Attiny 0/1 series to the AVR platform

### CODE REVIEW

**Comment by kriegsman** [comment]
I think we're ready to merge this PR once the (new) conflicts are resolved.   We just made some changes to the directory structure, so I think it'll be easy for you to resolve the conflicts and get this ready for merging.  Thank you for the help and the contribution!

**Comment by jasoncoon** [comment]
I couldn't figure out a better way, so I made a new PR from @freemovers fork to mine, fixed the merge conflicts, made the change suggested by @geekmomprojects, tested them on an ATtiny1604, and made a new PR: https://github.com/FastLED/FastLED/pull/1183

**Comment by ngyl88** [comment]
@jasoncoon @freemovers @kriegsman , please note that I created PR #1291 to resolve the merge conflicts. Please help to review the changes or test if possible. I don't have any board with me. =)

@kriegsman , from code maintenance point of view, the codes for AVR platform has grown to support AVR mega and AVR tiny. Before it's too late, maybe it's time to create platform subfolders for the 2 subs. The branch: https://github.com/FastLED/FastLED/tree/avrmega/platforms seems to share this idea, however it might have too much conflicts to resolve. It also seems to have some ATmega/ATtiny supports which we recently worked on, unsure if it's has valuable changes that we haven't absorb. This kind of refactoring will sometimes create regressions, unsure if we really want to start the clean ups. If we do, probably we could start collaborate in a new branch?

**Comment by kriegsman** [comment]
Thank you so much for these contributions.  And I like the idea of splitting out the AVR into multiple separate platforms.

@ngyl88 did you actually mean #1291 ?  Or a different PR to resolve the merge conflicts?

**Comment by ngyl88** [comment]
Oh no. There was a typo. It's https://github.com/FastLED/FastLED/pull/1292 instead.

**Comment by zackees** [comment]
Now merged

**Pull request closed without merging**
