### PR TITLE
included  time.h header file

### PR DESCRIPTION
**Pull request by DEVELOPER-IN-PROGRESS**

### CODE REVIEW

**Comment by focalintent** [comment]
Why?  And is it time.h or Time.h - the difference is important on systems with case sensitive file systems (eg Linux)

**Comment by DEVELOPER-IN-PROGRESS** [comment]
time.h

**Comment by focalintent** [comment]
Ok - and why are you adding this include here?

**Comment by focalintent** [comment]
What platforms do you need an explicit include of time.h on?

**Pull request closed without merging**
