### PR TITLE
avoid 200ms flicker every ~17.9 seconds with RMT driver

### PR DESCRIPTION
**Pull request by Jueff**
see also issue #1329

### CODE REVIEW

**Comment by ssilverman** [comment]
Why is the `led_sysdefs_esp32.h` change included?

**Comment by Jueff** [comment]
The  `led_sysdefs_esp32.h` change should not be part of the PR. I unfortunately did another commit to my repo after creating the PR, because I didn't know that this influences the PR.  So I reverted the `led_sysdefs_esp32.h` commit.

---> Jueff **force-pushed** the master branch from 514bdbc to 54c409e 7 days ago 

I thought, that the second commit will then not be part of PR anymore.

only the change in `clockless_rmt_esp32.cpp` is relevant.

**Comment by Jueff** [comment]
closed this PR because it contains extra files not relevant for the merge
replaced with PR #1336

**Comment by ssilverman** [comment]
For your reference, and to make it easier in the future, there’s no need to make a new PR. You could change things locally and then force push. PR’s aren’t set in stone.

**Pull request closed without merging**
