### PR TITLE
Documentation Updates

### PR DESCRIPTION
**Pull request by dmadison**
This PR updates the generated documentation so that it's comprehensive and easily accessible.

I've gone through the library with a fine-toothed comb and updated the documentation in all of the source files (`platforms` excluded) to the best of my ability. That included adding documentation where it was missing, formatting generic comments as Doxygen style, resolving references in comments, and grouping classes and functions into modules.

Doxygen has been updated to the latest version and the Doxyfile has been fixed so document generation works once more. I also applied a modern CSS theme so that the generated documentation is pleasing to the eye.

Finally, I created a GitHub Actions workflow to automatically generate and publish documentation to GitHub pages on new releases. This ensures that the public documentation will always reflect the latest version of the library.

**There are no <sup>intended</sup> functional changes to the code.** Some function signatures have been slightly tweaked so that signatures match between headers and source (e.g. 0551078, 306e753), and some preprocessor checks have been modified to add a `FASTLED_DOXYGEN` check so that documentation is always generated for specific platforms or library-dependent implementations. None of these changes intentionally modify normal behavior of the library.

Documentation Changes:
* Reviewed and updated the documentation in all main source files
* Minor updates to the README (versions, capitalization, etc.). A more comprehensive rewrite is probably worth tackling at a later date.

Doxygen Changes:
* Updated from Doxygen 1.8.18 to 1.9.3 (current version)
* Fixed input directory issues caused by change to repo structure (cb435ef)
* Excluded `platforms` directory from input files
* Included the .ino example files
* Added the [Doxygen Awesome theme](https://github.com/jothepro/doxygen-awesome-css)
* Added macro expansion and a number of predefined terms to improve documentation parsing and coverage
* Moved the detailed description to the top of every documentation page, in place of \brief

CI Changes:
* Created a GitHub Actions workflow to automatically generate docs and push them to the project website on release. Can also be triggered manually using workflow dispatch.
* Removed version-specific folder for hosted /docs/

[The documentation generated with these changes is currently live on my fork.](https://dmadison.github.io/FastLED/docs)

In the process of doing this I also found a number of snippets that appear to be unused and can possibly be removed. They are annotated with \todo tags for a future update.

I understand that the library is in maintenance mode, but please let me know if there's anything I can do to get this documentation merged.

### CODE REVIEW

**Comment by marmilicious** [comment]
Wow what a lot of great stuff. Excellent Dave. 👍🏻 

One thought-- In honor of Daniel Garcia I think we should continue to use his FastLED graphic/logo that we had on the G+ page back in the day. We also use it on the Reddit group. I dropped a copy here:  
https://imgur.com/a/Kvyn3uT

**Comment by dmadison** [comment]
Thanks Marc!

I didn't realize that there already was an icon. I'll swap that out right now.

**Comment by samguyer** [comment]
@dmadison Thank you so much -- this is an incredible contribution. Please make sure to add your name wherever appropriate -- you deserve the credit for this work.

**Comment by dmadison** [comment]
Thanks @samguyer. I'm fine with my name just on the commits 😃.

I've fixed the merge conflicts from the other pull requests. Everything is ready to go once again.

**Comment by dmadison** [comment]
Checking in on this. Do any maintainers have an ETA on when they could review and merge?

**Comment by kriegsman** [comment]
Thank you for the big help with getting the documentation in better shape!  Very much appreciated, and thank you for helping with FastLED!

**Pull request merged**
