### PR TITLE
ESP32 support using the RMT peripheral device

### PR DESCRIPTION
**Pull request by samguyer**
Developed together by Thomas Basler (@tbnobody) and myself based on ideas and code from a bunch of other people. Standing on the shoulders of giants!

Note that the clockless_block implementation is not done -- it's just a copy of the ESP8266 code.

### CODE REVIEW

**Comment by samguyer** [comment]
I'm not sure what the best strategy is for resolving the conflicts. I think that we should just overwrite the old files completely.

**Comment by tbnobody** [comment]
Just as a hint: @tbnobody == Thomas Basler, not Martin Falatic :)

**Comment by samguyer** [comment]
Oops! Sorry about that! All these secret names make it hard to give the right people credit.

**Comment by samguyer** [comment]
@tbnobody I guess the "tb" is a good hint. ;-)

**Comment by focalintent** [comment]
Sam - what's the state of your esp32 tree?  Probably best to get the latest state of it merged over - or is this the most recent set of changes?  (I don't believe it is, though)

**Comment by samguyer** [comment]
@focalintent I probably need to issue a new pull request. I think there might still be a more issue with the synchronization, but it is mostly very stable

**Comment by focalintent** [comment]
@samguyer, @kriegsman — any reason to not merge this back into master and spin a new release for it?

**Comment by samguyer** [comment]
@focalintent Let me submit a new pull request. I fixed some things.

**Comment by samguyer** [comment]
@focalintent I submitted the new pull request. One big benefit: it allows any number of controllers, rather than being limited to 8.

**Comment by samguyer** [comment]
It might have just updated automatically. Let me check.

**Comment by samguyer** [comment]
@focalintent Looks like all the recent changes are there. Fire away!

**Pull request merged**
