### PR TITLE
add qt py support!

### PR DESCRIPTION
**Pull request by ladyada**
a new samd21 variant

### CODE REVIEW

**Comment by marmilicious** [comment]
Adding more info for anyone interested.
Product page:  https://www.adafruit.com/product/4600
ATSAMD21 Datasheet:  https://cdn-learn.adafruit.com/assets/assets/000/044/363/original/samd21.pdf?1501106093

**Comment by marmilicious** [comment]
@ladyada Yes, in little bits here and there.  Loosing Dan Garcia was a pretty big blow to development and updates.  It's still slow going.

**Comment by ladyada** [comment]
im sorry to hear that :( would it be easier if we released a FastLED Adafruit Fork so we're not waiting on y'all?

**Comment by marmilicious** [comment]
@ladyada  That would be a good question for Mark @kriegsman

**Comment by kriegsman** [comment]
@samguyer and I (and @uberjay) are getting back into the groove a bit more now.  We've got weekly development sessions on our calendars, and we're hoping to also start including more contributors.

The idea of an Adafruit fork is a good one to think about, but let's see if we can keep up a better pace for now with just the original version.  We'll do what we can to prioritize support for the Adafruit boards since so many people use (and love) them.

**Comment by ladyada** [comment]
thank ya! one thing that may help improve contributions is a CI system. i can help implement the one we use for adafruit - it can be easily adapted to support a vast number of boards to make sure no compilation errors sneak in :)

**Comment by kriegsman** [comment]
THAT would be GREAT... you know better than anyone else really what a huge range of boards are out there, and how easy it is to have an oops.

**Pull request merged**
