### PR TITLE
Add FastLED as ESP-IDF component support

### PR DESCRIPTION
**Pull request by solhuebner**
Enables FastLED as ESP-IDF component support (with Arduino as component)

### CODE REVIEW

**Comment by solhuebner** [comment]
I should have been more verbose ;) This library already has a component.mk file but for full CMake support the CMakeLists.txt is also needed. That is especially useful if you want to use the [ESP-IDF](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/get-started/index.html) for the ESP32 (and its variants) for example, as they make use of CMake. That way you have more control but you also need to add all the 3rd party libraries as "components". Probably the most useful to start with is [ESP32-Arduino](https://github.com/espressif/arduino-esp32) but if you also want to use proven and loved libraries (like this one) you need to add the CMake files manually if they do not exist (what took me a bit to understand how it works). Some libraries like [ESP32-HUB75-MatrixPanel-I2S-DMA](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA) already implemented support, so I hope this one will too :)

**Comment by samguyer** [comment]
@solhuebner Thank you for your contribution! Would you mind taking a look at the related issue submitted by another user? I have not had a chance to look closely at it myself, but #1380 shows the compile problems.

**Comment by JustinOng** [comment]
Hello @samguyer, the compile issues when targeting the ESP32-S3 has been traced to a missing `F_CPU` definition, and a fix has been proposed at https://github.com/espressif/arduino-esp32/pull/7913. Is there anything else blocking the merge of this PR? I'm hoping to see this merged, rather than me creating another dead fork to merge this myself.

**Comment by JustinOng** [comment]
`src/platforms/esp/32/clockless_rmt_esp32.cpp` needs to be added to the list of sources.

**Comment by solhuebner** [comment]
> `src/platforms/esp/32/clockless_rmt_esp32.cpp` needs to be added to the list of sources.

Thanks. I will have a look over the weekend snd update the PR.

**Comment by solhuebner** [comment]
> `src/platforms/esp/32/clockless_rmt_esp32.cpp` needs to be added to the list of sources.

Added as requested :)

**Comment by JustinOng** [comment]
Looks good to me, thank you! At the moment, I'm just manually adding in your `CMakeLists.txt` with the following script:

```
cmake_minimum_required(VERSION 3.18)
include(FetchContent)

FetchContent_Declare(
  fastledlib
  GIT_REPOSITORY https://github.com/FastLED/FastLED.git
  GIT_TAG 4d73cddfe4bd2b370ee882b6f68769bf7f8309f4
  SOURCE_DIR fastled
)

FetchContent_GetProperties(fastledlib)
if(NOT fastledlib_POPULATED)
    FetchContent_Populate(fastledlib)
    configure_file(${CMAKE_CURRENT_LIST_DIR}/FastLED_CMakeLists.txt ${fastledlib_SOURCE_DIR}/CMakeLists.txt COPYONLY)
endif()

list(APPEND EXTRA_COMPONENT_DIRS ${fastledlib_SOURCE_DIR}/)
```

**Comment by kriegsman** [comment]
Thank you -- this is a great piece of support to have contributed.  Thanks for helping out with FastLED!

**Pull request merged**
