### PR TITLE
Added in manitou48 's fixes to FastLed for ItsyBitsy M4 (SADM51 boards)

### PR DESCRIPTION
**Pull request by devoh747**
Fixes the compile errors.

These are the fixes from maitou48 that I forked, tested. I didn;t code them just tested and it works great.
I have WS2812's running on an ItsyBitsy M4 working for me.

Again this is using the fixes from maitou48 https://github.com/manitou48/samd51/tree/master/FastLED-m4 as discussed in https://www.reddit.com/r/FastLED/comments/bnj1i6/can_we_get_the_samd51_support_merged_in_to/

### CODE REVIEW

**Comment by focalintent** [comment]
The led_sysdefs.h and platforms.h files belong in the root of the FastLED directory, not in platforms/arm/d51

**Comment by devoh747** [comment]
Do I need to fix that and reissue a pull request?  (Sorry total newb here and trying to learn)

**Comment by devoh747** [comment]
I fixed it on my end. I moved led_sysdefs.h and platforms.h files to the root of the FastLED directory. I had incorrectly placed them in platforms/arm/d51

**Comment by devoh747** [comment]
I'll issue a new pull request. Closing this one.

**Comment by devoh747** [comment]
Sorry about that, I fixed it.  Can you merge again or do I need to close and open a new PR?

 

Regards

 

  -Dave

**Comment by s-light** [comment]
@devoh747: you only need to create a pull-request once.
all changes you making are added to the request until it is merged.

**Comment by focalintent** [comment]
@s-light you're about 19 days behind - this PR's already been merged : )

**Comment by s-light** [comment]
yeah i know - it was thought as general info/help for devoh747
sorry for the noise..

**Pull request merged**
