### PR TITLE
Fix Teensy 4 SPI1_CLOCK

### LINKED ISSUE #1410: fastspi.h uses wrong variable for spi1
/FastLED/src/fastspi.h >> line 91,92: 

template<uint32_t SPI_SPEED>
class SPIOutput<SPI1_DATA, **SPI_CLOCK**, SPI_SPEED> : public Teensy4HardwareSPIOutput<SPI1_DATA, SPI1_CLOCK, SPI_SPEED, SPI1, 1> {};

The SPI_CLOCK should be SPI1_CLOCK

Corrected:

template<uint32_t SPI_SPEED>
class SPIOutput<SPI1_DATA, **SPI1_CLOCK**, SPI_SPEED> : public Teensy4HardwareSPIOutput<SPI1_DATA, SPI1_CLOCK, SPI_SPEED, SPI1, 1> {};

This bug was discovered by user [AntiDysentery](https://forum.pjrc.com/members/86791-AntiDysentery)
in this post: 
https://forum.pjrc.com/threads/70671-Teensy-4-1-with-FastLed-No-Hardware-SPI

### PR DESCRIPTION
**Pull request by ssilverman**
Ref: https://forum.pjrc.com/threads/70671-Teensy-4-1-with-FastLed-No-Hardware-SPI
Companion PR: https://github.com/PaulStoffregen/FastLED/pull/1

Fixes #1410

### CODE REVIEW

**Comment by ssilverman** [comment]
I'm not sure why the check is failing. (Something about missing `atmelavr`?)

**Comment by zackees** [comment]
Atmel failure is certainly a false positive.

Everything looks straightforward.

Can one of the FastLED owners please merge this?

@kriegsman
@dmadison
@sascha432
@samguyer

**Comment by smurphyUSI** [comment]
What are the chances that it fails because the built is testing on an old version of PlatformIO?

**Comment by zackees** [comment]
This test is currently failing in other builds.

https://github.com/FastLED/FastLED/runs/6960293459?check_suite_focus=true

**Comment by kriegsman** [comment]
I'm going to Close and Re-Open this PR to kick off a new round of checks, which I expect to succeed.  If it does, I'll merge it right away.

**Comment by kriegsman** [comment]
Thank you for this PR contribution, and thanks for the help with FastLED -- especially on Teensy!

**Pull request merged**
