### PR TITLE
Ensure getMaxRefreshRate() returns a non-zero default for Teensy 4.x

### LINKED ISSUE #912: teensy 4.0 only parallel output works, garbage output when FastLED.delay() is used
With a teensy 4.0 only parallel output works. When compiling with without the parallel output it compiles fine, but the output is garbage.

FastLED.delay() also creates garbage output. The same code changed to delay() works.

### PR DESCRIPTION
**Pull request by MartyMacGyver**
Fixes #912

### CODE REVIEW

**Comment by kriegsman** [comment]
Shall I merge this as-is with the "400" plugged in there, or would you like me to wait a bit yet?  I ask because it's marked "WIP".  Thanks for the help!

**Comment by MartyMacGyver** [comment]
I put it on there because I noticed last night that beyond about 64 LEDs the `FastLED.delay()` still causes artifacts on the Teensy 4.x. Dialing down the refresh rate compensates (per the wiki, it seems like setting it to 60 Hz works fine for 512 leds per lane, and 30 Hz for 1024, but I didn't exhaustively test higher values to failure).

**My question for you is, does `FastLED.delay()` cause flickering or other artifacts on other platforms if the refresh rate is too high for a give strip length and the default max refresh rate is too high for that configuration?** (Is `setMaxRefreshRate()` generally needed for long strips?) This is _excluding_ ESP32 using RMT with interrupts (which doesn't have this issue because of how it leverages that combination which is itself unusual versus other devices).

If the user is expected to self-throttle by limiting the max refresh rate for long LED strips, then this is ready to be merged and I'll take the WIP tag off.

**Comment by MartyMacGyver** [comment]
I want to add that just using regular `delay()` on the Teensy 4.x will also cause odd problems if the refresh rate isn't set right (particularly if the Serial connection is open). With my fix though, FastLED.delay() does the job (by default for shorter lengths, and for longer lengths if `setMaxRefreshRate()` is lowered accordingly).

So, I think my fix is helpful regardless (that default ought to be set), but the other oddities (which seem to be some kind of odd interaction between timers, interrupts, and Serial on the Teensy) are worthy of investigation but  out of scope here. Issue #1017 in particular grabs my attention, as I've seen that work some times and not others and it *seems* to be timer related as well. (This branch doesn't address that but I'm clearly seeing that problem as reported, and will see if I can help at all in narrowing it down.)

**Comment by MartyMacGyver** [comment]
WIP tag removed - ready to merge!

**Comment by kriegsman** [comment]
Thank you very much for the help, and the contributions!  Much appreciated!

**Pull request merged**
