### PR TITLE
Change CRGB constructors from inline to constexpr

### PR DESCRIPTION
**Pull request by vovagorodok**
Fixes: https://github.com/FastLED/FastLED/issues/1561

### CODE REVIEW

**Comment by kriegsman** [comment]
Thanks for helping out with FastLED, and thanks for helping nudge the code into more modern directions.   I like the constexpr.  Should some of these be constexpr _and_ inline, or just constexpr?  If the latter, I'll just accept the PR, but I wanted to ask explicitly first.

**Comment by vovagorodok** [comment]
There is a need for additional alignment on my side? Or will it be done in the next iteration?

**Comment by zackees** [comment]
What happens with older versions of Arduino IDE?

Is everyone using C++17 already and something like this would be safe?!?!

My gut feeling is that this would have to be put behind a #define so we don't break old compilers.

**Comment by kriegsman** [comment]
I think if this is C++11, we should go ahead and merge it, and say thanks for helping modernize the code base a little bit.  If it turns out that there's some unintended consequence down the road, we can come back and address that then.

**Comment by kriegsman** [comment]
Thank you very much for helping modernize the code base a bit, and thanks for the help with the FastLED library!

**Pull request merged**
