### PR TITLE
Fixed a bunch of typos

### PR DESCRIPTION
**Pull request by WoLpH**

### CODE REVIEW

**Comment by NicoHood** [comment]
You should really fix this thing and simply close it. In case you forgot about this PR.

**Comment by focalintent** [comment]
PR no longer valid, as the code layout has changed drastically.

**Comment by WoLpH** [comment]
Perhaps I'm looking at the wrong branch but it still appears to be the same. Should merge cleanly

**Comment by focalintent** [comment]
You are - all the current work is being done on th 3.1 branch which had major layout/file changes.   I manually fixed the comment typos that you had found in them.  I'm not accepting anything else into master until I merge 3.1 back into it.

**Comment by WoLpH** [comment]
Ok, great :)

Thanks for the quick response

**Pull request closed without merging**
