### PR TITLE
attempt a fix for #339 - guard waitfully against a race condition - a…

### PR DESCRIPTION
**Pull request by focalintent**
…nd also make sure we reset the TCF flag whenever we write something out

### CODE REVIEW

**Comment by marmilicious** [comment]
(Daniel, was this update to fix the "freezing"/"hanging" issue?  If not, apologies for commenting in the wrong spot.)
I just tried out the latest 3.1.3 release (#pragma message: FastLED version 3.001.003) with a Teensy 3.0 and LPD8806 (32 pixel strip) and it hung up.

Using:  Arduino 1.6.11, (the new final) Teensyduino 1.30 [I did not install any libraries with Teensyduino, but as always grabbed the latest FastLED here after I saw you put out 3.1.3]
Testing with this slightly modified cylon code:  http://pastebin.com/wRX2U00B
 I'm game to test anything you might recommend. 
-marc

**Comment by focalintent** [comment]
@marmilicious   Huh - I wonder if you're hitting a different bug than what folks are talking about in #339  - since multiple other people reported that fix taking care of the hangup problem for them (I spun the release more to get the esp8266 stuff out there - I still haven't had a chance to try to chase this down with hardware and see what's going on with it).

I also haven't done any work/testing w/Arduino 1.6.11 or teensyduino 1.30 yet

**Comment by marmilicious** [comment]
Ok, to continue testing I just uninstalled 1.6.11, and installed 1.6.8 and teensduino 1.28 and got the hang again.
I know 1.6.8 and teensduino 1.28 worked great for me in the past.  I'm pretty sure this same hardware setup with 1.68 & teensyduino 1.28 with LPD8806 and also with an APA102 strip was working back in April/May time frame.  Can you point me to an older FastLED release/update that might be a good test?

**Comment by marmilicious** [comment]
Daniel, for now I went back to FastLED 3.1.0 [ https://github.com/FastLED/FastLED/archive/v3.1.0.zip ] and everything is running fine.  (But someday I hope to get back on the latest FastLED goodness so like all the other cool cats I can get my ESP8266 grove on.)

I tested with a Teensy 3.0, IDE 1.6.8, Teensduino 1.28, and then IDE 1.6.11, Teensduino 1.30, with LPD8806 and APA102 strips.  No hangs.

**Pull request merged**
