### PR TITLE
Update T1H and T0H timing to fix flicker on UNO R4

### PR DESCRIPTION
**Pull request by sparky650**
I found that the timing gave a flicker on WS2812 and WS2818 LED drivers, I think this is due to the T1H timing being >1050ns. The new timing puts the timing at ~800ns for T1H and ~340ns for T0L. This has been tested on genuine UNO R4 WiFi and Minima boards with WS2818B LED strips and WS2812B LED modules

### CODE REVIEW

**Comment by ocack** [comment]
Hello the community,

Here is the context:
I have an Arduino R3 UNO that controls succesfully a WS2811 Led strips by using FastLed 3.6.0
The arduino has also to receive MIDI messages through a shield.
All works pretty good excepted the loss of some MIDI messages but this is not the subject and it's actually a well-known issue
[Interrupt-problems](https://github.com/FastLED/FastLED/wiki/Interrupt-problems)

Here is the issue:
I have recently bought an Arduino R4 Minima for replacing my R3 (and avoiding interrupt problems on MIDI).
Next, I have installed the "Arduino UNO R4 Boards" to the Arduino IDE
I quickly had a the well-known compilation error (platform R4 is not yet supported by FastLed)
Thus, I had to install the non official FastLed release "renesas: initial porting for UNO R4" [#1523](https://github.com/FastLED/FastLED/pull/1523)

All were compiling without error but the strip led were flickering randomly.
Then, I've found this topic and try the sparky650's fix.
But it has not solved the issue for my case :-(
Note that we haved tried the fix by compiling our sketch with chipset WS2811, WS2811_400, WS2812 and WS2812B
We also tried with the sketch "FirstLight.ino" example attached in FastLed library

Conclusion:
It seems that this fix doesn't solve the flickering issue when using an Arduino R4 Minima and WS2811 strip led
I am open for trying any advice useful for potentially fix the Issue.
I own a Arduino R4 Minima and WS2811 strip leds.

Regards

**Comment by architolk** [comment]
I had the same issue with a string of WS2813 LEDs and a genuine Arduino UNO R4 WiFi. This PR fixed the issue

**Comment by samguyer** [comment]
@sparky650 Thanks for your work on this issue! We are accepting this PR, but if you discover anything new about the problem let us know or submit a new PR. Looking at the code, I'm wondering if you can elaborate on what the timing adjustment does -- TBH I did not understand the purpose of the original adjustment (i.e., why is any adjustment to T1L/T0L necessary?)

**Comment by ocack** [comment]
Hi,
is there any news about the test with the ws2811 ?
I can help if needed, I am not a novice in C programmation.
We have the hardware to test.
I just miss the specification of the ws2821 and the renesas platform.
How do you plan to test it ?

Regards

**Comment by ocack** [comment]
Can anybody help me for this issue ?
Difficult to beleive that I am the only one that interfaces an Arduino R4 with FastLed and a strip WS2811 !?
I would like to help the community to move forward on that issue.
Which tests can I do ?
Which documentation do I need for trying to fixing that ?
Regards

**Pull request merged**
